// Code generated by GoHT v0.9.1 - DO NOT EDIT.
// https://github.com/stackus/goht

package commands

import "context"
import "io"
import "github.com/stackus/goht"

// Any template can be included into another template; assuming that
// you have not created a circular reference, this will not cause the
// compiler to loop but will instead cause the generated code to
// run into errors.
// When you are creating a template that will be included into another
// template, you can use the `@children` command to indicate where any
// optional content from the calling template should be inserted.
// The `@children` command is used in combination with the rendering
// code syntax `=`.

type ChildrenExampleTemplate struct {
	goht.SlotTemplate
}

// ChildrenExample returns a new instance of ChildrenExampleTemplate.
// Slots: children.
func ChildrenExample() *ChildrenExampleTemplate {
	return &ChildrenExampleTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>Child Template</p>\n<p>\nThe following was passed in from the calling template:\n"); __err != nil {
			return
		}
		if __children, __hasChildren := __slots.Has("children"); __hasChildren {
			if __err = __children.Render(ctx, __buf); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for ChildrenExampleTemplate and returns a new instance.
func (t *ChildrenExampleTemplate) Slot(name string, templates ...goht.Template) *ChildrenExampleTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for ChildrenExampleTemplate.
func (t *ChildrenExampleTemplate) WithChildren(templates ...goht.Template) *ChildrenExampleTemplate {
	return t.Slot("children", templates...)
}

type HamlChildrenExampleTemplate struct {
	goht.SlotTemplate
}

// HamlChildrenExample returns a new instance of HamlChildrenExampleTemplate.
// Slots: children.
func HamlChildrenExample() *HamlChildrenExampleTemplate {
	return &HamlChildrenExampleTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>Haml Child Template</p>\n<p>\nThe following was passed in from the calling template:\n"); __err != nil {
			return
		}
		if __children, __hasChildren := __slots.Has("children"); __hasChildren {
			if __err = __children.Render(ctx, __buf); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlChildrenExampleTemplate and returns a new instance.
func (t *HamlChildrenExampleTemplate) Slot(name string, templates ...goht.Template) *HamlChildrenExampleTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlChildrenExampleTemplate.
func (t *HamlChildrenExampleTemplate) WithChildren(templates ...goht.Template) *HamlChildrenExampleTemplate {
	return t.Slot("children", templates...)
}

type SlimChildrenExampleTemplate struct {
	goht.SlotTemplate
}

// SlimChildrenExample returns a new instance of SlimChildrenExampleTemplate.
// Slots: children.
func SlimChildrenExample() *SlimChildrenExampleTemplate {
	return &SlimChildrenExampleTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>Slim Child Template</p><p>The following was passed in from the calling template:"); __err != nil {
			return
		}
		if __children, __hasChildren := __slots.Has("children"); __hasChildren {
			if __err = __children.Render(ctx, __buf); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for SlimChildrenExampleTemplate and returns a new instance.
func (t *SlimChildrenExampleTemplate) Slot(name string, templates ...goht.Template) *SlimChildrenExampleTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlimChildrenExampleTemplate.
func (t *SlimChildrenExampleTemplate) WithChildren(templates ...goht.Template) *SlimChildrenExampleTemplate {
	return t.Slot("children", templates...)
}
