// Code generated by GoHT v0.8.5 - DO NOT EDIT.
// https://github.com/stackus/goht

package filters

import "context"
import "io"
import "github.com/stackus/goht"

// You can include JavaScript into your templates using the JavaScript
// filter `:javascript`. You may include interpolation values within
// the JavaScript code to have them replaced with values at render time.

var name = "Bob"

type JavaScriptTemplate struct {
	goht.SlotTemplate
}

// JavaScript returns a new instance of JavaScriptTemplate.
// Slots: children.
func JavaScript() *JavaScriptTemplate {
	return &JavaScriptTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<script>\nconsole.log(\"Hello "); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(name)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("!\");\n</script>"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for JavaScriptTemplate and returns a new instance.
func (t *JavaScriptTemplate) Slot(name string, templates ...goht.Template) *JavaScriptTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for JavaScriptTemplate.
func (t *JavaScriptTemplate) WithChildren(templates ...goht.Template) *JavaScriptTemplate {
	return t.Slot("children", templates...)
}

type HamlJavaScriptTemplate struct {
	goht.SlotTemplate
}

// HamlJavaScript returns a new instance of HamlJavaScriptTemplate.
// Slots: children.
func HamlJavaScript() *HamlJavaScriptTemplate {
	return &HamlJavaScriptTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<script>\nconsole.log(\"Hello "); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(name)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("!\");\n</script>"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlJavaScriptTemplate and returns a new instance.
func (t *HamlJavaScriptTemplate) Slot(name string, templates ...goht.Template) *HamlJavaScriptTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlJavaScriptTemplate.
func (t *HamlJavaScriptTemplate) WithChildren(templates ...goht.Template) *HamlJavaScriptTemplate {
	return t.Slot("children", templates...)
}

type SlimJavaScriptTemplate struct {
	goht.SlotTemplate
}

// SlimJavaScript returns a new instance of SlimJavaScriptTemplate.
// Slots: children.
func SlimJavaScript() *SlimJavaScriptTemplate {
	return &SlimJavaScriptTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<script>\nconsole.log(\"Hello "); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(name)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("!\");\n</script>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for SlimJavaScriptTemplate and returns a new instance.
func (t *SlimJavaScriptTemplate) Slot(name string, templates ...goht.Template) *SlimJavaScriptTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlimJavaScriptTemplate.
func (t *SlimJavaScriptTemplate) WithChildren(templates ...goht.Template) *SlimJavaScriptTemplate {
	return t.Slot("children", templates...)
}
