// Code generated by GoHT v0.9.1 - DO NOT EDIT.
// https://github.com/stackus/goht

package attributes

import "context"
import "io"
import "github.com/stackus/goht"

// Additional attributes may be added to an element using the `@attributes`
// command. This command accepts a list of additional attributes in the
// following formats:
// - A map[string]bool - Any attribute with a true value is added as is.
// - A map[string]string - Any attribute with a non-empty string value is
//   added as is.

var boolAttrs = map[string]bool{
	"disabled": true,
	"checked":  false,
}
var strAttrs = map[string]string{
	"type":  "checkbox",
	"value": "foo",
}

type AttributesCmdTemplate struct {
	goht.SlotTemplate
}

// AttributesCmd returns a new instance of AttributesCmdTemplate.
// Slots: children.
func AttributesCmd() *AttributesCmdTemplate {
	return &AttributesCmdTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<input"); __err != nil {
			return
		}
		var __var1 string
		__var1, __err = goht.BuildAttributeList(boolAttrs, strAttrs)
		if __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" " + __var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(">"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for AttributesCmdTemplate and returns a new instance.
func (t *AttributesCmdTemplate) Slot(name string, templates ...goht.Template) *AttributesCmdTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for AttributesCmdTemplate.
func (t *AttributesCmdTemplate) WithChildren(templates ...goht.Template) *AttributesCmdTemplate {
	return t.Slot("children", templates...)
}

type HamlAttributesCmdTemplate struct {
	goht.SlotTemplate
}

// HamlAttributesCmd returns a new instance of HamlAttributesCmdTemplate.
// Slots: children.
func HamlAttributesCmd() *HamlAttributesCmdTemplate {
	return &HamlAttributesCmdTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<input"); __err != nil {
			return
		}
		var __var1 string
		__var1, __err = goht.BuildAttributeList(boolAttrs, strAttrs)
		if __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" " + __var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(">"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlAttributesCmdTemplate and returns a new instance.
func (t *HamlAttributesCmdTemplate) Slot(name string, templates ...goht.Template) *HamlAttributesCmdTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlAttributesCmdTemplate.
func (t *HamlAttributesCmdTemplate) WithChildren(templates ...goht.Template) *HamlAttributesCmdTemplate {
	return t.Slot("children", templates...)
}

type SlimAttributesCmdTemplate struct {
	goht.SlotTemplate
}

// SlimAttributesCmd returns a new instance of SlimAttributesCmdTemplate.
// Slots: children.
func SlimAttributesCmd() *SlimAttributesCmdTemplate {
	return &SlimAttributesCmdTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<input"); __err != nil {
			return
		}
		var __var1 string
		__var1, __err = goht.BuildAttributeList(boolAttrs, strAttrs)
		if __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" " + __var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(">\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for SlimAttributesCmdTemplate and returns a new instance.
func (t *SlimAttributesCmdTemplate) Slot(name string, templates ...goht.Template) *SlimAttributesCmdTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlimAttributesCmdTemplate.
func (t *SlimAttributesCmdTemplate) WithChildren(templates ...goht.Template) *SlimAttributesCmdTemplate {
	return t.Slot("children", templates...)
}
