// Code generated by GoHT v0.9.0 - DO NOT EDIT.
// https://github.com/stackus/goht

package attributes

import "context"
import "io"
import "github.com/stackus/goht"

var id = "my-id"
var content = "Content"

// GoHT supports HTML style attributes. You can use the same syntax as you would
// in HTML. The only difference is that you need to use a hash and curly braces to
// denote dynamic values.

type HamlHtmlAttributesTemplate struct {
	goht.SlotTemplate
}

// HamlHtmlAttributes returns a new instance of HamlHtmlAttributesTemplate.
// Slots: children.
func HamlHtmlAttributes() *HamlHtmlAttributesTemplate {
	return &HamlHtmlAttributesTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"foo\" id=\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(goht.EscapeString(id) + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(">Content</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlHtmlAttributesTemplate and returns a new instance.
func (t *HamlHtmlAttributesTemplate) Slot(name string, templates ...goht.Template) *HamlHtmlAttributesTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlHtmlAttributesTemplate.
func (t *HamlHtmlAttributesTemplate) WithChildren(templates ...goht.Template) *HamlHtmlAttributesTemplate {
	return t.Slot("children", templates...)
}

type SlimHtmlAttributesTemplate struct {
	goht.SlotTemplate
}

// SlimHtmlAttributes returns a new instance of SlimHtmlAttributesTemplate.
// Slots: children.
func SlimHtmlAttributes() *SlimHtmlAttributesTemplate {
	return &SlimHtmlAttributesTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"foo\" id=\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(goht.EscapeString(id) + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(">Content</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for SlimHtmlAttributesTemplate and returns a new instance.
func (t *SlimHtmlAttributesTemplate) Slot(name string, templates ...goht.Template) *SlimHtmlAttributesTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlimHtmlAttributesTemplate.
func (t *SlimHtmlAttributesTemplate) WithChildren(templates ...goht.Template) *SlimHtmlAttributesTemplate {
	return t.Slot("children", templates...)
}

type HamlMultiLineHtmlAttributesTemplate struct {
	goht.SlotTemplate
}

// HamlMultiLineHtmlAttributes returns a new instance of HamlMultiLineHtmlAttributesTemplate.
// Slots: children.
func HamlMultiLineHtmlAttributes() *HamlMultiLineHtmlAttributesTemplate {
	return &HamlMultiLineHtmlAttributesTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"foo\" id=\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(goht.EscapeString(id) + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(">Content</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlMultiLineHtmlAttributesTemplate and returns a new instance.
func (t *HamlMultiLineHtmlAttributesTemplate) Slot(name string, templates ...goht.Template) *HamlMultiLineHtmlAttributesTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlMultiLineHtmlAttributesTemplate.
func (t *HamlMultiLineHtmlAttributesTemplate) WithChildren(templates ...goht.Template) *HamlMultiLineHtmlAttributesTemplate {
	return t.Slot("children", templates...)
}

type SlimMultiLineHtmlAttributesTemplate struct {
	goht.SlotTemplate
}

// SlimMultiLineHtmlAttributes returns a new instance of SlimMultiLineHtmlAttributesTemplate.
// Slots: children.
func SlimMultiLineHtmlAttributes() *SlimMultiLineHtmlAttributesTemplate {
	return &SlimMultiLineHtmlAttributesTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"foo\" id=\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(goht.EscapeString(id) + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(">Content</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for SlimMultiLineHtmlAttributesTemplate and returns a new instance.
func (t *SlimMultiLineHtmlAttributesTemplate) Slot(name string, templates ...goht.Template) *SlimMultiLineHtmlAttributesTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlimMultiLineHtmlAttributesTemplate.
func (t *SlimMultiLineHtmlAttributesTemplate) WithChildren(templates ...goht.Template) *SlimMultiLineHtmlAttributesTemplate {
	return t.Slot("children", templates...)
}

type HamlHtmlWithComplexNamesTemplate struct {
	goht.SlotTemplate
}

// HamlHtmlWithComplexNames returns a new instance of HamlHtmlWithComplexNamesTemplate.
// Slots: children.
func HamlHtmlWithComplexNames() *HamlHtmlWithComplexNamesTemplate {
	return &HamlHtmlWithComplexNamesTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div href=\"https://github.com/stackus/goht\" :class=\"show ? &#39;&#39; : &#39;hidden&#39;\" @click=\"show = !show\">Content</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlHtmlWithComplexNamesTemplate and returns a new instance.
func (t *HamlHtmlWithComplexNamesTemplate) Slot(name string, templates ...goht.Template) *HamlHtmlWithComplexNamesTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlHtmlWithComplexNamesTemplate.
func (t *HamlHtmlWithComplexNamesTemplate) WithChildren(templates ...goht.Template) *HamlHtmlWithComplexNamesTemplate {
	return t.Slot("children", templates...)
}

type SlimHtmlWithComplexNamesTemplate struct {
	goht.SlotTemplate
}

// SlimHtmlWithComplexNames returns a new instance of SlimHtmlWithComplexNamesTemplate.
// Slots: children.
func SlimHtmlWithComplexNames() *SlimHtmlWithComplexNamesTemplate {
	return &SlimHtmlWithComplexNamesTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div href=\"https://github.com/stackus/goht\" :class=\"show ? &#39;&#39; : &#39;hidden&#39;\" @click=\"show = !show\">Content</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for SlimHtmlWithComplexNamesTemplate and returns a new instance.
func (t *SlimHtmlWithComplexNamesTemplate) Slot(name string, templates ...goht.Template) *SlimHtmlWithComplexNamesTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlimHtmlWithComplexNamesTemplate.
func (t *SlimHtmlWithComplexNamesTemplate) WithChildren(templates ...goht.Template) *SlimHtmlWithComplexNamesTemplate {
	return t.Slot("children", templates...)
}
