// Code generated by GoHT v0.9.1 - DO NOT EDIT.
// https://github.com/stackus/goht

package comments

import "context"
import "io"
import "github.com/stackus/goht"

// You may use ruby style comments to completely remove a line or
// even a block of nested elements.
// This is accomplished by using the `-#` syntax.
// This is useful for removing elements that are only used for
// documentation purposes.
// The nested elements commented out with this syntax will be
// not the parsed by the compiler and will not be included in the
// output.

type RubyStyleTemplate struct {
	goht.SlotTemplate
}

// RubyStyle returns a new instance of RubyStyleTemplate.
// Slots: children.
func RubyStyle() *RubyStyleTemplate {
	return &RubyStyleTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>This is the only paragraph in the output.</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for RubyStyleTemplate and returns a new instance.
func (t *RubyStyleTemplate) Slot(name string, templates ...goht.Template) *RubyStyleTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for RubyStyleTemplate.
func (t *RubyStyleTemplate) WithChildren(templates ...goht.Template) *RubyStyleTemplate {
	return t.Slot("children", templates...)
}

type HamlRubyStyleTemplate struct {
	goht.SlotTemplate
}

// HamlRubyStyle returns a new instance of HamlRubyStyleTemplate.
// Slots: children.
func HamlRubyStyle() *HamlRubyStyleTemplate {
	return &HamlRubyStyleTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>This is the only paragraph in the output.</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlRubyStyleTemplate and returns a new instance.
func (t *HamlRubyStyleTemplate) Slot(name string, templates ...goht.Template) *HamlRubyStyleTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlRubyStyleTemplate.
func (t *HamlRubyStyleTemplate) WithChildren(templates ...goht.Template) *HamlRubyStyleTemplate {
	return t.Slot("children", templates...)
}

// In the Slim syntax "RubyStyle" comments use a "/" to indicate the
// start of the comment

type SlimRubyStyleTemplate struct {
	goht.SlotTemplate
}

// SlimRubyStyle returns a new instance of SlimRubyStyleTemplate.
// Slots: children.
func SlimRubyStyle() *SlimRubyStyleTemplate {
	return &SlimRubyStyleTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>This is the only paragraph in the output.</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for SlimRubyStyleTemplate and returns a new instance.
func (t *SlimRubyStyleTemplate) Slot(name string, templates ...goht.Template) *SlimRubyStyleTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlimRubyStyleTemplate.
func (t *SlimRubyStyleTemplate) WithChildren(templates ...goht.Template) *SlimRubyStyleTemplate {
	return t.Slot("children", templates...)
}

// Ruby style comments can comment nested content.

type RubyStyleNestedTemplate struct {
	goht.SlotTemplate
}

// RubyStyleNested returns a new instance of RubyStyleNestedTemplate.
// Slots: children.
func RubyStyleNested() *RubyStyleNestedTemplate {
	return &RubyStyleNestedTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>This is the only paragraph in the output.</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for RubyStyleNestedTemplate and returns a new instance.
func (t *RubyStyleNestedTemplate) Slot(name string, templates ...goht.Template) *RubyStyleNestedTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for RubyStyleNestedTemplate.
func (t *RubyStyleNestedTemplate) WithChildren(templates ...goht.Template) *RubyStyleNestedTemplate {
	return t.Slot("children", templates...)
}

type HamlRubyStyleNestedTemplate struct {
	goht.SlotTemplate
}

// HamlRubyStyleNested returns a new instance of HamlRubyStyleNestedTemplate.
// Slots: children.
func HamlRubyStyleNested() *HamlRubyStyleNestedTemplate {
	return &HamlRubyStyleNestedTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>This is the only paragraph in the output.</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlRubyStyleNestedTemplate and returns a new instance.
func (t *HamlRubyStyleNestedTemplate) Slot(name string, templates ...goht.Template) *HamlRubyStyleNestedTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlRubyStyleNestedTemplate.
func (t *HamlRubyStyleNestedTemplate) WithChildren(templates ...goht.Template) *HamlRubyStyleNestedTemplate {
	return t.Slot("children", templates...)
}

type SlimRubyStyleNestedTemplate struct {
	goht.SlotTemplate
}

// SlimRubyStyleNested returns a new instance of SlimRubyStyleNestedTemplate.
// Slots: children.
func SlimRubyStyleNested() *SlimRubyStyleNestedTemplate {
	return &SlimRubyStyleNestedTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>This is the only paragraph in the output.</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for SlimRubyStyleNestedTemplate and returns a new instance.
func (t *SlimRubyStyleNestedTemplate) Slot(name string, templates ...goht.Template) *SlimRubyStyleNestedTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlimRubyStyleNestedTemplate.
func (t *SlimRubyStyleNestedTemplate) WithChildren(templates ...goht.Template) *SlimRubyStyleNestedTemplate {
	return t.Slot("children", templates...)
}
