// Code generated by hamlet - DO NOT EDIT.

package __renders

import (
	"bytes"
	"context"
	"github.com/stackus/hamlet"
	"io"
)

func wrapper() hamlet.Template {
	return hamlet.TemplateFunc(func(ctx context.Context, __w io.Writer) (__err error) {
		__buf, __isBuf := __w.(*bytes.Buffer)
		if !__isBuf {
			__buf = hamlet.GetBuffer()
			defer hamlet.ReleaseBuffer(__buf)
		}
		var __children hamlet.Template
		ctx, __children = hamlet.PopChildren(ctx)
		_ = __children
		if _, __err = __buf.WriteString("<p class=\"wrapper\">"); __err != nil {
			return
		}
		if __err = __children.Render(ctx, __buf); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</p>"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __buf.WriteTo(__w)
		}
		return
	})
}

func content() hamlet.Template {
	return hamlet.TemplateFunc(func(ctx context.Context, __w io.Writer) (__err error) {
		__buf, __isBuf := __w.(*bytes.Buffer)
		if !__isBuf {
			__buf = hamlet.GetBuffer()
			defer hamlet.ReleaseBuffer(__buf)
		}
		var __children hamlet.Template
		ctx, __children = hamlet.PopChildren(ctx)
		_ = __children
		__var1 := hamlet.TemplateFunc(func(ctx context.Context, __w io.Writer) (__err error) {
			__buf, __isBuf := __w.(*bytes.Buffer)
			if !__isBuf {
				__buf = hamlet.GetBuffer()
				defer hamlet.ReleaseBuffer(__buf)
			}
			if _, __err = __buf.WriteString("<div class=\"content\">This is the content</div>"); __err != nil {
				return
			}
			if !__isBuf {
				_, __err = io.Copy(__w, __buf)
			}
			return
		})
		if __err = wrapper().Render(hamlet.PushChildren(ctx, __var1), __w); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __buf.WriteTo(__w)
		}
		return
	})
}
