// Code generated by GoHT v0.9.1 - DO NOT EDIT.
// https://github.com/stackus/goht

package integration

import "context"
import "io"
import "github.com/stackus/goht"

type LayoutTemplate struct {
	goht.SlotTemplate
}

// Layout returns a new instance of LayoutTemplate.
// Slots: children, header, content.
func Layout() *LayoutTemplate {
	return &LayoutTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"layout\"><header>"); __err != nil {
			return
		}
		if __slot, __hasSlot := __slots.Has("header"); __hasSlot {
			if __err = __slot.Render(ctx, __buf); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("</header><main>"); __err != nil {
			return
		}
		if __slot, __hasSlot := __slots.Has("content"); __hasSlot {
			if __err = __slot.Render(ctx, __buf); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("</main><footer>"); __err != nil {
			return
		}
		if __children, __hasChildren := __slots.Has("children"); __hasChildren {
			if __err = __children.Render(ctx, __buf); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("</footer></div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children", "header", "content")}
}

// Slot sets a named slot for LayoutTemplate and returns a new instance.
func (t *LayoutTemplate) Slot(name string, templates ...goht.Template) *LayoutTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for LayoutTemplate.
func (t *LayoutTemplate) WithChildren(templates ...goht.Template) *LayoutTemplate {
	return t.Slot("children", templates...)
}

// WithHeader sets the "header" slot for LayoutTemplate.
func (t *LayoutTemplate) WithHeader(templates ...goht.Template) *LayoutTemplate {
	return t.Slot("header", templates...)
}

// WithContent sets the "content" slot for LayoutTemplate.
func (t *LayoutTemplate) WithContent(templates ...goht.Template) *LayoutTemplate {
	return t.Slot("content", templates...)
}

type HeaderTemplate struct {
	goht.SlotTemplate
}

// Header returns a new instance of HeaderTemplate.
// Slots: children.
func Header(title string) *HeaderTemplate {
	return &HeaderTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<h1>"); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(title)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</h1>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HeaderTemplate and returns a new instance.
func (t *HeaderTemplate) Slot(name string, templates ...goht.Template) *HeaderTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HeaderTemplate.
func (t *HeaderTemplate) WithChildren(templates ...goht.Template) *HeaderTemplate {
	return t.Slot("children", templates...)
}

type PanelTemplate struct {
	goht.SlotTemplate
}

// Panel returns a new instance of PanelTemplate.
// Slots: children, body.
func Panel() *PanelTemplate {
	return &PanelTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"panel\"><ul>"); __err != nil {
			return
		}
		if __slot, __hasSlot := __slots.Has("body"); __hasSlot {
			if __err = __slot.Render(ctx, __buf); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("</ul></div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children", "body")}
}

// Slot sets a named slot for PanelTemplate and returns a new instance.
func (t *PanelTemplate) Slot(name string, templates ...goht.Template) *PanelTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for PanelTemplate.
func (t *PanelTemplate) WithChildren(templates ...goht.Template) *PanelTemplate {
	return t.Slot("children", templates...)
}

// WithBody sets the "body" slot for PanelTemplate.
func (t *PanelTemplate) WithBody(templates ...goht.Template) *PanelTemplate {
	return t.Slot("body", templates...)
}

type ListItemTemplate struct {
	goht.SlotTemplate
}

// ListItem returns a new instance of ListItemTemplate.
// Slots: children.
func ListItem(value string) *ListItemTemplate {
	return &ListItemTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<li>"); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(value)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</li>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for ListItemTemplate and returns a new instance.
func (t *ListItemTemplate) Slot(name string, templates ...goht.Template) *ListItemTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for ListItemTemplate.
func (t *ListItemTemplate) WithChildren(templates ...goht.Template) *ListItemTemplate {
	return t.Slot("children", templates...)
}

type FooterTemplate struct {
	goht.SlotTemplate
}

// Footer returns a new instance of FooterTemplate.
// Slots: children.
func Footer() *FooterTemplate {
	return &FooterTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<small>footer</small>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for FooterTemplate and returns a new instance.
func (t *FooterTemplate) Slot(name string, templates ...goht.Template) *FooterTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for FooterTemplate.
func (t *FooterTemplate) WithChildren(templates ...goht.Template) *FooterTemplate {
	return t.Slot("children", templates...)
}
