// Code generated by hamlet - DO NOT EDIT.

package indents

import "bytes"
import "context"
import "io"
import "github.com/stackus/hamlet"

// You may use tabs to indent the Haml templates.
// Hamlet does not change how indenting works in Haml. If you want
// to use tabs, you must use tabs consistently.
// Do not mix tabs and spaces in a single template. You would be
// asking for trouble IMO but you may use tabs in one template and
// spaces in another.

func UsingTabs() hamlet.Template {
	return hamlet.TemplateFunc(func(ctx context.Context, __w io.Writer) (__err error) {
		__buf, __isBuf := __w.(*bytes.Buffer)
		if !__isBuf {
			__buf = hamlet.GetBuffer()
			defer hamlet.ReleaseBuffer(__buf)
		}
		var __children hamlet.Template
		ctx, __children = hamlet.PopChildren(ctx)
		_ = __children
		if _, __err = __buf.WriteString("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\"><title>\nHello World\n</title>\n</head>\n<body>\n<h1>\nHello World\n</h1>\n<p>\nHello World\n</p>\n</body>\n</html>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(hamlet.NukeWhitespace(__buf.Bytes()))
		}
		return
	})
}
