// Code generated by GoHT v0.8.5 - DO NOT EDIT.
// https://github.com/stackus/goht

package testdata

import "context"
import "io"
import "github.com/stackus/goht"

type CommentsTestTemplate struct {
	goht.SlotTemplate
}

// CommentsTest returns a new instance of CommentsTestTemplate.
// Slots: none.
func CommentsTest() *CommentsTestTemplate {
	return &CommentsTestTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		if _, __err = __buf.WriteString("<p>before</p>\n<!--this is a HTML comment-->\n<p>after</p>\n<p>last</p>\n<div>---</div>\n<p>before</p>\n<!--\nthis is a HTML comment\n-->\n<p>after</p>\n<p>last</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})}
}

// Slot sets a named slot for CommentsTestTemplate and returns a new instance.
func (t *CommentsTestTemplate) Slot(name string, templates ...goht.Template) *CommentsTestTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}
