// Code generated by GoHT v0.9.0 - DO NOT EDIT.
// https://github.com/stackus/goht

package testdata

import "context"
import "io"
import "github.com/stackus/goht"

type ConditionalsTestTemplate struct {
	goht.SlotTemplate
}

// ConditionalsTest returns a new instance of ConditionalsTestTemplate.
// Slots: children.
func ConditionalsTest(v bool) *ConditionalsTestTemplate {
	return &ConditionalsTestTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>before</p>\n"); __err != nil {
			return
		}
		if v {
			if _, __err = __buf.WriteString("<p>the condition was true</p>\n"); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("<p>after</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for ConditionalsTestTemplate and returns a new instance.
func (t *ConditionalsTestTemplate) Slot(name string, templates ...goht.Template) *ConditionalsTestTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for ConditionalsTestTemplate.
func (t *ConditionalsTestTemplate) WithChildren(templates ...goht.Template) *ConditionalsTestTemplate {
	return t.Slot("children", templates...)
}
