// Code generated by GoHT v0.8.2 - DO NOT EDIT.
// https://github.com/stackus/goht

package testdata

import "context"
import "io"
import "github.com/stackus/goht"

func ElementsTest() goht.Template {
	return goht.TemplateFunc(func(ctx context.Context, __w io.Writer, __sts ...goht.SlottedTemplate) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		if _, __err = __buf.WriteString("<!DOCTYPE html>\n<html>\n<body>\n<div id=\"main\" class=\"wrapper\">\n<article>\n<h1>Article Title</h1>\n</article>\n<p>Article content</p>\n<footer>\n<p>Article footer</p>\n</footer>\n</div>\n<footer class=\"wrapper\">\n<p>Footer content</p>\n</footer>\n</body>\n</html>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})
}
