// Code generated by GoHT v0.8.5 - DO NOT EDIT.
// https://github.com/stackus/goht

package testdata

import "context"
import "io"
import "github.com/stackus/goht"

type HtmlAttributesTestTemplate struct {
	goht.SlotTemplate
}

// HtmlAttributesTest returns a new instance of HtmlAttributesTestTemplate.
// Slots: children.
func HtmlAttributesTest() *HtmlAttributesTestTemplate {
	return &HtmlAttributesTestTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p class=\"static\">Static paren attr</p>\n<p class=\"b\" id=\"a\">Multiple paren attrs</p>\n"); __err != nil {
			return
		}
		dynVal := "dynamic"
		if _, __err = __buf.WriteString("<p id=\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(goht.EscapeString(dynVal) + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(">Dynamic paren attr</p>\n<button disabled>Boolean paren attr</button>\n<p class=\"multiline\" id=\"paren\">Multiline paren attrs</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HtmlAttributesTestTemplate and returns a new instance.
func (t *HtmlAttributesTestTemplate) Slot(name string, templates ...goht.Template) *HtmlAttributesTestTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HtmlAttributesTestTemplate.
func (t *HtmlAttributesTestTemplate) WithChildren(templates ...goht.Template) *HtmlAttributesTestTemplate {
	return t.Slot("children", templates...)
}
