// Code generated by GoHT v0.8.5 - DO NOT EDIT.
// https://github.com/stackus/goht

package testdata

import "context"
import "io"
import "github.com/stackus/goht"

func HtmlAttributesTest() goht.Template {
	return goht.TemplateFunc(func(ctx context.Context, __w io.Writer, __sts ...goht.SlottedTemplate) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		if _, __err = __buf.WriteString("<p class=\"static\">Static paren attr</p>\n<p class=\"b\" id=\"a\">Multiple paren attrs</p>\n"); __err != nil {
			return
		}
		dynVal := "dynamic"
		if _, __err = __buf.WriteString("<p id=\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(goht.EscapeString(dynVal) + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(">Dynamic paren attr</p>\n<button disabled>Boolean paren attr</button>\n<p class=\"multiline\" id=\"paren\">Multiline paren attrs</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})
}
