// Code generated by GoHT v0.8.5 - DO NOT EDIT.
// https://github.com/stackus/goht

package testdata

import "context"
import "io"
import "github.com/stackus/goht"

var foo = "bar"

type InterpolationTestTemplate struct {
	goht.SlotTemplate
}

// InterpolationTest returns a new instance of InterpolationTestTemplate.
// Slots: children.
func InterpolationTest() *InterpolationTestTemplate {
	return &InterpolationTestTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>This is "); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(foo)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for InterpolationTestTemplate and returns a new instance.
func (t *InterpolationTestTemplate) Slot(name string, templates ...goht.Template) *InterpolationTestTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for InterpolationTestTemplate.
func (t *InterpolationTestTemplate) WithChildren(templates ...goht.Template) *InterpolationTestTemplate {
	return t.Slot("children", templates...)
}
