// Code generated by GoHT v0.8.5 - DO NOT EDIT.
// https://github.com/stackus/goht

package testdata

import "context"
import "io"
import "github.com/stackus/goht"

type NewlinesTestTemplate struct {
	goht.SlotTemplate
}

// NewlinesTest returns a new instance of NewlinesTestTemplate.
// Slots: children.
func NewlinesTest() *NewlinesTestTemplate {
	return &NewlinesTestTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"first\"></div>\n<div class=\"second\">Content</div>\n<div class=\"third\"></div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for NewlinesTestTemplate and returns a new instance.
func (t *NewlinesTestTemplate) Slot(name string, templates ...goht.Template) *NewlinesTestTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for NewlinesTestTemplate.
func (t *NewlinesTestTemplate) WithChildren(templates ...goht.Template) *NewlinesTestTemplate {
	return t.Slot("children", templates...)
}
