// Code generated by GoHT v0.9.0 - DO NOT EDIT.
// https://github.com/stackus/goht

package testdata

import "context"
import "io"
import "github.com/stackus/goht"

type PackageTestTemplate struct {
	goht.SlotTemplate
}

// PackageTest returns a new instance of PackageTestTemplate.
// Slots: children.
func PackageTest() *PackageTestTemplate {
	return &PackageTestTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("This is a package test.\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for PackageTestTemplate and returns a new instance.
func (t *PackageTestTemplate) Slot(name string, templates ...goht.Template) *PackageTestTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for PackageTestTemplate.
func (t *PackageTestTemplate) WithChildren(templates ...goht.Template) *PackageTestTemplate {
	return t.Slot("children", templates...)
}
