// Code generated by GoHT v0.8.5 - DO NOT EDIT.
// https://github.com/stackus/goht

package testdata

import "context"
import "io"
import "github.com/stackus/goht"

type ChildrenTestTemplate struct {
	goht.SlotTemplate
}

// ChildrenTest returns a new instance of ChildrenTestTemplate.
// Slots: children.
func ChildrenTest(v string) *ChildrenTestTemplate {
	return &ChildrenTestTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"passed-in\">"); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(v)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</div>\n<div class=\"children\">\n"); __err != nil {
			return
		}
		if __children, __hasChildren := __slots.Has("children"); __hasChildren {
			if __err = __children.Render(ctx, __buf); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("</div>\n<div class=\"after\">After children</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for ChildrenTestTemplate and returns a new instance.
func (t *ChildrenTestTemplate) Slot(name string, templates ...goht.Template) *ChildrenTestTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for ChildrenTestTemplate.
func (t *ChildrenTestTemplate) WithChildren(templates ...goht.Template) *ChildrenTestTemplate {
	return t.Slot("children", templates...)
}

type RenderTestTemplate struct {
	goht.SlotTemplate
}

// RenderTest returns a new instance of RenderTestTemplate.
// Slots: children.
func RenderTest() *RenderTestTemplate {
	return &RenderTestTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"parent\">\n<div class=\"local\">This is local content</div>\n"); __err != nil {
			return
		}
		__var1 := goht.Fragment{goht.TemplateFunc(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
			__buf, __isBuf := __w.(goht.Buffer)
			if !__isBuf {
				__buf = goht.GetBuffer()
				defer goht.ReleaseBuffer(__buf)
			}
			if _, __err = __buf.WriteString("<div class=\"child\">This is child content</div>\n"); __err != nil {
				return
			}
			if !__isBuf {
				_, __err = io.Copy(__w, __buf)
			}
			return
		})}
		if __err = ChildrenTest("This is passed-in content").WithChildren(__var1...).Render(ctx, __buf); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("<div class=\"after\">After parent</div>\n</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for RenderTestTemplate and returns a new instance.
func (t *RenderTestTemplate) Slot(name string, templates ...goht.Template) *RenderTestTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for RenderTestTemplate.
func (t *RenderTestTemplate) WithChildren(templates ...goht.Template) *RenderTestTemplate {
	return t.Slot("children", templates...)
}

type WrapperTestTemplate struct {
	goht.SlotTemplate
}

// WrapperTest returns a new instance of WrapperTestTemplate.
// Slots: children.
func WrapperTest() *WrapperTestTemplate {
	return &WrapperTestTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"wrapper\">\n<div class=\"list\">\n"); __err != nil {
			return
		}
		if __children, __hasChildren := __slots.Has("children"); __hasChildren {
			if __err = __children.Render(ctx, __buf); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("</div>\n</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for WrapperTestTemplate and returns a new instance.
func (t *WrapperTestTemplate) Slot(name string, templates ...goht.Template) *WrapperTestTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for WrapperTestTemplate.
func (t *WrapperTestTemplate) WithChildren(templates ...goht.Template) *WrapperTestTemplate {
	return t.Slot("children", templates...)
}

type WrappedTestTemplate struct {
	goht.SlotTemplate
}

// WrappedTest returns a new instance of WrappedTestTemplate.
// Slots: children.
func WrappedTest(v string) *WrappedTestTemplate {
	return &WrappedTestTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"item\">"); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(v)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for WrappedTestTemplate and returns a new instance.
func (t *WrappedTestTemplate) Slot(name string, templates ...goht.Template) *WrappedTestTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for WrappedTestTemplate.
func (t *WrappedTestTemplate) WithChildren(templates ...goht.Template) *WrappedTestTemplate {
	return t.Slot("children", templates...)
}

type NestedRenderTestTemplate struct {
	goht.SlotTemplate
}

// NestedRenderTest returns a new instance of NestedRenderTestTemplate.
// Slots: children.
func NestedRenderTest() *NestedRenderTestTemplate {
	return &NestedRenderTestTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		__var1 := goht.Fragment{goht.TemplateFunc(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
			__buf, __isBuf := __w.(goht.Buffer)
			if !__isBuf {
				__buf = goht.GetBuffer()
				defer goht.ReleaseBuffer(__buf)
			}
			if __err = WrappedTest("first").Render(ctx, __buf); __err != nil {
				return
			}
			if __err = WrappedTest("second").Render(ctx, __buf); __err != nil {
				return
			}
			if !__isBuf {
				_, __err = io.Copy(__w, __buf)
			}
			return
		})}
		if __err = WrapperTest().WithChildren(__var1...).Render(ctx, __buf); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for NestedRenderTestTemplate and returns a new instance.
func (t *NestedRenderTestTemplate) Slot(name string, templates ...goht.Template) *NestedRenderTestTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for NestedRenderTestTemplate.
func (t *NestedRenderTestTemplate) WithChildren(templates ...goht.Template) *NestedRenderTestTemplate {
	return t.Slot("children", templates...)
}

type SlotTestTemplate struct {
	goht.SlotTemplate
}

// SlotTest returns a new instance of SlotTestTemplate.
// Slots: children, first, second, third.
func SlotTest() *SlotTestTemplate {
	return &SlotTestTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"wrapper\">\n"); __err != nil {
			return
		}
		if __slot, __hasSlot := __slots.Has("first"); __hasSlot {
			if __err = __slot.Render(ctx, __buf); __err != nil {
				return
			}
		}
		if __slot, __hasSlot := __slots.Has("second"); __hasSlot {
			if __err = __slot.Render(ctx, __buf); __err != nil {
				return
			}
		}
		if __slot, __hasSlot := __slots.Has("third"); __hasSlot {
			if __err = __slot.Render(ctx, __buf); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children", "first", "second", "third")}
}

// Slot sets a named slot for SlotTestTemplate and returns a new instance.
func (t *SlotTestTemplate) Slot(name string, templates ...goht.Template) *SlotTestTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlotTestTemplate.
func (t *SlotTestTemplate) WithChildren(templates ...goht.Template) *SlotTestTemplate {
	return t.Slot("children", templates...)
}

// WithFirst sets the "first" slot for SlotTestTemplate.
func (t *SlotTestTemplate) WithFirst(templates ...goht.Template) *SlotTestTemplate {
	return t.Slot("first", templates...)
}

// WithSecond sets the "second" slot for SlotTestTemplate.
func (t *SlotTestTemplate) WithSecond(templates ...goht.Template) *SlotTestTemplate {
	return t.Slot("second", templates...)
}

// WithThird sets the "third" slot for SlotTestTemplate.
func (t *SlotTestTemplate) WithThird(templates ...goht.Template) *SlotTestTemplate {
	return t.Slot("third", templates...)
}

type SlotWithDefaultTestTemplate struct {
	goht.SlotTemplate
}

// SlotWithDefaultTest returns a new instance of SlotWithDefaultTestTemplate.
// Slots: children, first, second, third.
func SlotWithDefaultTest() *SlotWithDefaultTestTemplate {
	return &SlotWithDefaultTestTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"wrapper\">\n"); __err != nil {
			return
		}
		if __slot, __hasSlot := __slots.Has("first"); __hasSlot {
			if __err = __slot.Render(ctx, __buf); __err != nil {
				return
			}
		} else {
			if _, __err = __buf.WriteString("<p>Default first</p>\n"); __err != nil {
				return
			}
		}
		if __slot, __hasSlot := __slots.Has("second"); __hasSlot {
			if __err = __slot.Render(ctx, __buf); __err != nil {
				return
			}
		} else {
			if _, __err = __buf.WriteString("<p>Default second</p>\n"); __err != nil {
				return
			}
		}
		if __slot, __hasSlot := __slots.Has("third"); __hasSlot {
			if __err = __slot.Render(ctx, __buf); __err != nil {
				return
			}
		} else {
			if _, __err = __buf.WriteString("<p>Default third</p>\n"); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children", "first", "second", "third")}
}

// Slot sets a named slot for SlotWithDefaultTestTemplate and returns a new instance.
func (t *SlotWithDefaultTestTemplate) Slot(name string, templates ...goht.Template) *SlotWithDefaultTestTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlotWithDefaultTestTemplate.
func (t *SlotWithDefaultTestTemplate) WithChildren(templates ...goht.Template) *SlotWithDefaultTestTemplate {
	return t.Slot("children", templates...)
}

// WithFirst sets the "first" slot for SlotWithDefaultTestTemplate.
func (t *SlotWithDefaultTestTemplate) WithFirst(templates ...goht.Template) *SlotWithDefaultTestTemplate {
	return t.Slot("first", templates...)
}

// WithSecond sets the "second" slot for SlotWithDefaultTestTemplate.
func (t *SlotWithDefaultTestTemplate) WithSecond(templates ...goht.Template) *SlotWithDefaultTestTemplate {
	return t.Slot("second", templates...)
}

// WithThird sets the "third" slot for SlotWithDefaultTestTemplate.
func (t *SlotWithDefaultTestTemplate) WithThird(templates ...goht.Template) *SlotWithDefaultTestTemplate {
	return t.Slot("third", templates...)
}
