// Code generated by GoHT v0.8.0 - DO NOT EDIT.
// https://github.com/stackus/goht

package testdata

import "context"
import "io"
import "github.com/stackus/goht"

func SlimTemplate() goht.Template {
	return goht.TemplateFunc(func(ctx context.Context, __w io.Writer, __sts ...goht.SlottedTemplate) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		if _, __err = __buf.WriteString("<!DOCTYPE html><html lang=\"en\"><head><title>Hello World</title></head><body><p>Hello World</p>"); __err != nil {
			return
		}
		for i := 0; i < 10; i++ {
			if _, __err = __buf.WriteString("<p>Iteration: "); __err != nil {
				return
			}
			var __var1 string
			if __var1, __err = goht.CaptureErrors(goht.EscapeString(goht.FormatString("%d", i))); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(__var1); __err != nil {
				return
			}
			if _, __err = __buf.WriteString("</p>"); __err != nil {
				return
			}
		}
		if true {
			if _, __err = __buf.WriteString("<p>Condition is true</p>"); __err != nil {
				return
			}
		} else if false {
			if _, __err = __buf.WriteString("<p>Condition is false</p>"); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("</body></html>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})
}
