// Code generated by GoHT v0.9.0 - DO NOT EDIT.
// https://github.com/stackus/goht

package testdata

import "context"
import "io"
import "github.com/stackus/goht"

type SlimTemplateTemplate struct {
	goht.SlotTemplate
}

// SlimTemplate returns a new instance of SlimTemplateTemplate.
// Slots: children.
func SlimTemplate() *SlimTemplateTemplate {
	return &SlimTemplateTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<!DOCTYPE html><html lang=\"en\"><head><title>Hello World</title></head><body><p>Hello World</p>"); __err != nil {
			return
		}
		for i := 0; i < 10; i++ {
			if _, __err = __buf.WriteString("<p>Iteration: "); __err != nil {
				return
			}
			var __var1 string
			if __var1, __err = goht.CaptureErrors(goht.EscapeString(goht.FormatString("%d", i))); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(__var1); __err != nil {
				return
			}
			if _, __err = __buf.WriteString("</p>"); __err != nil {
				return
			}
		}
		if true {
			if _, __err = __buf.WriteString("<p>Condition is true</p>"); __err != nil {
				return
			}
		} else if false {
			if _, __err = __buf.WriteString("<p>Condition is false</p>"); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("</body></html>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for SlimTemplateTemplate and returns a new instance.
func (t *SlimTemplateTemplate) Slot(name string, templates ...goht.Template) *SlimTemplateTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlimTemplateTemplate.
func (t *SlimTemplateTemplate) WithChildren(templates ...goht.Template) *SlimTemplateTemplate {
	return t.Slot("children", templates...)
}
