// Code generated by GoHT v0.8.5 - DO NOT EDIT.
// https://github.com/stackus/goht

package testdata

import "context"
import "io"
import "github.com/stackus/goht"

type TypedNoSlotsTemplate struct {
	goht.SlotTemplate
}

// TypedNoSlots returns a new instance of TypedNoSlotsTemplate.
// Slots: none.
func TypedNoSlots() *TypedNoSlotsTemplate {
	return &TypedNoSlotsTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		if _, __err = __buf.WriteString("<p>no slots</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	})}
}

// Slot sets a named slot for TypedNoSlotsTemplate and returns a new instance.
func (t *TypedNoSlotsTemplate) Slot(name string, templates ...goht.Template) *TypedNoSlotsTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

type TypedOneSlotTemplate struct {
	goht.SlotTemplate
}

// TypedOneSlot returns a new instance of TypedOneSlotTemplate.
// Slots: header.
func TypedOneSlot() *TypedOneSlotTemplate {
	return &TypedOneSlotTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		if __slot := goht.GetSlot(ctx, "header"); __slot != nil {
			if __err = __slot.Render(ctx, __buf); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "header")}
}

// Slot sets a named slot for TypedOneSlotTemplate and returns a new instance.
func (t *TypedOneSlotTemplate) Slot(name string, templates ...goht.Template) *TypedOneSlotTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithHeader sets the "header" slot for TypedOneSlotTemplate.
func (t *TypedOneSlotTemplate) WithHeader(templates ...goht.Template) *TypedOneSlotTemplate {
	return t.Slot("header", templates...)
}

type TypedMultipleSlotsTemplate struct {
	goht.SlotTemplate
}

// TypedMultipleSlots returns a new instance of TypedMultipleSlotsTemplate.
// Slots: main-content, sidebar_2.
func TypedMultipleSlots() *TypedMultipleSlotsTemplate {
	return &TypedMultipleSlotsTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		if __slot := goht.GetSlot(ctx, "main-content"); __slot != nil {
			if __err = __slot.Render(ctx, __buf); __err != nil {
				return
			}
		}
		if __slot := goht.GetSlot(ctx, "sidebar_2"); __slot != nil {
			if __err = __slot.Render(ctx, __buf); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "main-content", "sidebar_2")}
}

// Slot sets a named slot for TypedMultipleSlotsTemplate and returns a new instance.
func (t *TypedMultipleSlotsTemplate) Slot(name string, templates ...goht.Template) *TypedMultipleSlotsTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithMainContent sets the "main-content" slot for TypedMultipleSlotsTemplate.
func (t *TypedMultipleSlotsTemplate) WithMainContent(templates ...goht.Template) *TypedMultipleSlotsTemplate {
	return t.Slot("main-content", templates...)
}

// WithSidebar2 sets the "sidebar_2" slot for TypedMultipleSlotsTemplate.
func (t *TypedMultipleSlotsTemplate) WithSidebar2(templates ...goht.Template) *TypedMultipleSlotsTemplate {
	return t.Slot("sidebar_2", templates...)
}

type TypedFallbackSlotTemplate struct {
	goht.SlotTemplate
}

// TypedFallbackSlot returns a new instance of TypedFallbackSlotTemplate.
// Slots: footer.
func TypedFallbackSlot() *TypedFallbackSlotTemplate {
	return &TypedFallbackSlotTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		if __slot := goht.GetSlot(ctx, "footer"); __slot != nil {
			if __err = __slot.Render(ctx, __buf); __err != nil {
				return
			}
		} else {
			if _, __err = __buf.WriteString("<p>fallback</p>"); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "footer")}
}

// Slot sets a named slot for TypedFallbackSlotTemplate and returns a new instance.
func (t *TypedFallbackSlotTemplate) Slot(name string, templates ...goht.Template) *TypedFallbackSlotTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithFooter sets the "footer" slot for TypedFallbackSlotTemplate.
func (t *TypedFallbackSlotTemplate) WithFooter(templates ...goht.Template) *TypedFallbackSlotTemplate {
	return t.Slot("footer", templates...)
}

type TypedDuplicateSlotTemplate struct {
	goht.SlotTemplate
}

// TypedDuplicateSlot returns a new instance of TypedDuplicateSlotTemplate.
// Slots: content.
func TypedDuplicateSlot() *TypedDuplicateSlotTemplate {
	return &TypedDuplicateSlotTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var __children goht.Template
		ctx, __children = goht.PopChildren(ctx)
		_ = __children
		if __slot := goht.GetSlot(ctx, "content"); __slot != nil {
			if __err = __slot.Render(ctx, __buf); __err != nil {
				return
			}
		}
		if __slot := goht.GetSlot(ctx, "content"); __slot != nil {
			if __err = __slot.Render(ctx, __buf); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "content")}
}

// Slot sets a named slot for TypedDuplicateSlotTemplate and returns a new instance.
func (t *TypedDuplicateSlotTemplate) Slot(name string, templates ...goht.Template) *TypedDuplicateSlotTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithContent sets the "content" slot for TypedDuplicateSlotTemplate.
func (t *TypedDuplicateSlotTemplate) WithContent(templates ...goht.Template) *TypedDuplicateSlotTemplate {
	return t.Slot("content", templates...)
}
