// Code generated by GoHT v0.9.1 - DO NOT EDIT.
// https://github.com/stackus/goht

package testdata

import "context"
import "io"
import "github.com/stackus/goht"

type WhitespaceTestTemplate struct {
	goht.SlotTemplate
}

// WhitespaceTest returns a new instance of WhitespaceTestTemplate.
// Slots: children.
func WhitespaceTest() *WhitespaceTestTemplate {
	return &WhitespaceTestTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>\n<span>Content</span>\n>☢~<span>\nOuter\n</span>~☢<<span>Content</span>\n</p>\n<p>\n<span>Content</span>\n<span>~☢<\nInner\n>☢~</span>\n<span>Content</span>\n</p>\n<p>\n<span>Content</span>\n>☢~<span>~☢<\nBoth\n>☢~</span>~☢<<span>Content</span>\n</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for WhitespaceTestTemplate and returns a new instance.
func (t *WhitespaceTestTemplate) Slot(name string, templates ...goht.Template) *WhitespaceTestTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for WhitespaceTestTemplate.
func (t *WhitespaceTestTemplate) WithChildren(templates ...goht.Template) *WhitespaceTestTemplate {
	return t.Slot("children", templates...)
}
