// Code generated by GoHT v0.8.5 - DO NOT EDIT.
// https://github.com/stackus/goht

package example

import "context"
import "io"
import "github.com/stackus/goht"
import (
	fmt "fmt"
	"strings"
)

// Just like in Go files you can specify imports that are needed
// by your Go code or Go code inlined into the Goht template.
// Any imports that you specify here will be combined with the
// imports used by the Goht compiler itself. Duplicate imports
// will be removed.

type ImportExampleTemplate struct {
	goht.SlotTemplate
}

// ImportExample returns a new instance of ImportExampleTemplate.
// Slots: children.
func ImportExample() *ImportExampleTemplate {
	return &ImportExampleTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>"); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(fmt.Sprintf("Hello, %s!", strings.TrimSuffix("World!", "!")))); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for ImportExampleTemplate and returns a new instance.
func (t *ImportExampleTemplate) Slot(name string, templates ...goht.Template) *ImportExampleTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for ImportExampleTemplate.
func (t *ImportExampleTemplate) WithChildren(templates ...goht.Template) *ImportExampleTemplate {
	return t.Slot("children", templates...)
}

type HamlImportExampleTemplate struct {
	goht.SlotTemplate
}

// HamlImportExample returns a new instance of HamlImportExampleTemplate.
// Slots: children.
func HamlImportExample() *HamlImportExampleTemplate {
	return &HamlImportExampleTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>"); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(fmt.Sprintf("Hello, %s!", strings.TrimSuffix("World!", "!")))); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlImportExampleTemplate and returns a new instance.
func (t *HamlImportExampleTemplate) Slot(name string, templates ...goht.Template) *HamlImportExampleTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlImportExampleTemplate.
func (t *HamlImportExampleTemplate) WithChildren(templates ...goht.Template) *HamlImportExampleTemplate {
	return t.Slot("children", templates...)
}

type SlimImportExampleTemplate struct {
	goht.SlotTemplate
}

// SlimImportExample returns a new instance of SlimImportExampleTemplate.
// Slots: children.
func SlimImportExample() *SlimImportExampleTemplate {
	return &SlimImportExampleTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>"); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(fmt.Sprintf("Hello, %s!", strings.TrimSuffix("World!", "!")))); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for SlimImportExampleTemplate and returns a new instance.
func (t *SlimImportExampleTemplate) Slot(name string, templates ...goht.Template) *SlimImportExampleTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlimImportExampleTemplate.
func (t *SlimImportExampleTemplate) WithChildren(templates ...goht.Template) *SlimImportExampleTemplate {
	return t.Slot("children", templates...)
}
