// Code generated by hamlet - DO NOT EDIT.

package example

import (
	"bytes"
	"context"
	"github.com/stackus/hamlet"
	"io"
)

// You can include Go code to handle conditional and loop statements
// in your Hamlet templates.

var isAdmin = true

func Conditional() hamlet.Template {
	return hamlet.TemplateFunc(func(ctx context.Context, __w io.Writer) (__err error) {
		__buf, __isBuf := __w.(*bytes.Buffer)
		if !__isBuf {
			__buf = hamlet.GetBuffer()
			defer hamlet.ReleaseBuffer(__buf)
		}
		var __children hamlet.Template
		ctx, __children = hamlet.PopChildren(ctx)
		_ = __children
		if _, __err = __buf.WriteString("<div class=\"actions\">\n"); __err != nil {
			return
		}
		if isAdmin {
			if _, __err = __buf.WriteString("<button>~☢<\nEdit content\n>☢~</button>\n"); __err != nil {
				return
			}
		} else {
			if _, __err = __buf.WriteString("<button>Login</button>\n"); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("<button>View content</button>\n</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(hamlet.NukeWhitespace(__buf.Bytes()))
		}
		return
	})
}
