// Code generated by GoHT v0.9.1 - DO NOT EDIT.
// https://github.com/stackus/goht

package example

import "context"
import "io"
import "github.com/stackus/goht"
import (
	"fmt"
)

// You can include Go code to handle conditional and loop statements
// in your Goht templates.

var isAdmin = true

type ConditionalTemplate struct {
	goht.SlotTemplate
}

// Conditional returns a new instance of ConditionalTemplate.
// Slots: children.
func Conditional() *ConditionalTemplate {
	return &ConditionalTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"actions\">\n"); __err != nil {
			return
		}
		if isAdmin {
			if _, __err = __buf.WriteString("<button>~☢<\nEdit content\n>☢~</button>\n"); __err != nil {
				return
			}
		} else {
			if _, __err = __buf.WriteString("<button>Login</button>\n"); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("<button>View content</button>\n</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for ConditionalTemplate and returns a new instance.
func (t *ConditionalTemplate) Slot(name string, templates ...goht.Template) *ConditionalTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for ConditionalTemplate.
func (t *ConditionalTemplate) WithChildren(templates ...goht.Template) *ConditionalTemplate {
	return t.Slot("children", templates...)
}

type HamlConditionalTemplate struct {
	goht.SlotTemplate
}

// HamlConditional returns a new instance of HamlConditionalTemplate.
// Slots: children.
func HamlConditional() *HamlConditionalTemplate {
	return &HamlConditionalTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"actions\">\n"); __err != nil {
			return
		}
		if isAdmin {
			if _, __err = __buf.WriteString("<button>~☢<\nEdit content\n>☢~</button>\n"); __err != nil {
				return
			}
		} else {
			if _, __err = __buf.WriteString("<button>Login</button>\n"); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("<button>View content</button>\n</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlConditionalTemplate and returns a new instance.
func (t *HamlConditionalTemplate) Slot(name string, templates ...goht.Template) *HamlConditionalTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlConditionalTemplate.
func (t *HamlConditionalTemplate) WithChildren(templates ...goht.Template) *HamlConditionalTemplate {
	return t.Slot("children", templates...)
}

type SlimConditionalTemplate struct {
	goht.SlotTemplate
}

// SlimConditional returns a new instance of SlimConditionalTemplate.
// Slots: children.
func SlimConditional() *SlimConditionalTemplate {
	return &SlimConditionalTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"actions\">"); __err != nil {
			return
		}
		if isAdmin {
			if _, __err = __buf.WriteString("<button><Edit>content</Edit></button>"); __err != nil {
				return
			}
		} else {
			if _, __err = __buf.WriteString("<button>Login</button>"); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("<button>View content</button></div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for SlimConditionalTemplate and returns a new instance.
func (t *SlimConditionalTemplate) Slot(name string, templates ...goht.Template) *SlimConditionalTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlimConditionalTemplate.
func (t *SlimConditionalTemplate) WithChildren(templates ...goht.Template) *SlimConditionalTemplate {
	return t.Slot("children", templates...)
}

// However, we are using Haml and so we're into shortcuts. We can
// continue to write out the brackets or we can use the shorthand
// syntax.
// The short hand form simply drops the opening and closing brackets
// for statements that wrap around children.
// Shorthand statements include:
// for, if, else, else if, switch

type ShorthandConditionalTemplate struct {
	goht.SlotTemplate
}

// ShorthandConditional returns a new instance of ShorthandConditionalTemplate.
// Slots: children.
func ShorthandConditional() *ShorthandConditionalTemplate {
	return &ShorthandConditionalTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"actions\">\n"); __err != nil {
			return
		}
		if isAdmin {
			if _, __err = __buf.WriteString("<button>~☢<\nEdit content\n>☢~</button>\n"); __err != nil {
				return
			}
		} else {
			if _, __err = __buf.WriteString("<button>Login</button>\n"); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("<button>View content</button>\n</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for ShorthandConditionalTemplate and returns a new instance.
func (t *ShorthandConditionalTemplate) Slot(name string, templates ...goht.Template) *ShorthandConditionalTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for ShorthandConditionalTemplate.
func (t *ShorthandConditionalTemplate) WithChildren(templates ...goht.Template) *ShorthandConditionalTemplate {
	return t.Slot("children", templates...)
}

type HamlShorthandConditionalTemplate struct {
	goht.SlotTemplate
}

// HamlShorthandConditional returns a new instance of HamlShorthandConditionalTemplate.
// Slots: children.
func HamlShorthandConditional() *HamlShorthandConditionalTemplate {
	return &HamlShorthandConditionalTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"actions\">\n"); __err != nil {
			return
		}
		if isAdmin {
			if _, __err = __buf.WriteString("<button>~☢<\nEdit content\n>☢~</button>\n"); __err != nil {
				return
			}
		} else {
			if _, __err = __buf.WriteString("<button>Login</button>\n"); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("<button>View content</button>\n</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlShorthandConditionalTemplate and returns a new instance.
func (t *HamlShorthandConditionalTemplate) Slot(name string, templates ...goht.Template) *HamlShorthandConditionalTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlShorthandConditionalTemplate.
func (t *HamlShorthandConditionalTemplate) WithChildren(templates ...goht.Template) *HamlShorthandConditionalTemplate {
	return t.Slot("children", templates...)
}

type SlimShorthandConditionalTemplate struct {
	goht.SlotTemplate
}

// SlimShorthandConditional returns a new instance of SlimShorthandConditionalTemplate.
// Slots: children.
func SlimShorthandConditional() *SlimShorthandConditionalTemplate {
	return &SlimShorthandConditionalTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"actions\">"); __err != nil {
			return
		}
		if isAdmin {
			if _, __err = __buf.WriteString("<button>Edit content</button>"); __err != nil {
				return
			}
		} else {
			if _, __err = __buf.WriteString("<button>Login</button>"); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("<button>View content</button></div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for SlimShorthandConditionalTemplate and returns a new instance.
func (t *SlimShorthandConditionalTemplate) Slot(name string, templates ...goht.Template) *SlimShorthandConditionalTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlimShorthandConditionalTemplate.
func (t *SlimShorthandConditionalTemplate) WithChildren(templates ...goht.Template) *SlimShorthandConditionalTemplate {
	return t.Slot("children", templates...)
}

// With a switch statement, we can use the case and default keywords
// but we will need to nest these statements if we're using the
// shorthand syntax. (win some, lose some)

type ShorthandSwitchTemplate struct {
	goht.SlotTemplate
}

// ShorthandSwitch returns a new instance of ShorthandSwitchTemplate.
// Slots: children.
func ShorthandSwitch() *ShorthandSwitchTemplate {
	return &ShorthandSwitchTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"actions\">\n"); __err != nil {
			return
		}
		switch isAdmin {
		case true:
			if _, __err = __buf.WriteString("<button>~☢<\nEdit content\n>☢~</button>\n"); __err != nil {
				return
			}
		case false:
			if _, __err = __buf.WriteString("<button>Login</button>\n"); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("<button>View content</button>\n</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for ShorthandSwitchTemplate and returns a new instance.
func (t *ShorthandSwitchTemplate) Slot(name string, templates ...goht.Template) *ShorthandSwitchTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for ShorthandSwitchTemplate.
func (t *ShorthandSwitchTemplate) WithChildren(templates ...goht.Template) *ShorthandSwitchTemplate {
	return t.Slot("children", templates...)
}

type HamlShorthandSwitchTemplate struct {
	goht.SlotTemplate
}

// HamlShorthandSwitch returns a new instance of HamlShorthandSwitchTemplate.
// Slots: children.
func HamlShorthandSwitch() *HamlShorthandSwitchTemplate {
	return &HamlShorthandSwitchTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"actions\">\n"); __err != nil {
			return
		}
		switch isAdmin {
		case true:
			if _, __err = __buf.WriteString("<button>~☢<\nEdit content\n>☢~</button>\n"); __err != nil {
				return
			}
		case false:
			if _, __err = __buf.WriteString("<button>Login</button>\n"); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("<button>View content</button>\n</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlShorthandSwitchTemplate and returns a new instance.
func (t *HamlShorthandSwitchTemplate) Slot(name string, templates ...goht.Template) *HamlShorthandSwitchTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlShorthandSwitchTemplate.
func (t *HamlShorthandSwitchTemplate) WithChildren(templates ...goht.Template) *HamlShorthandSwitchTemplate {
	return t.Slot("children", templates...)
}

type SlimShorthandSwitchTemplate struct {
	goht.SlotTemplate
}

// SlimShorthandSwitch returns a new instance of SlimShorthandSwitchTemplate.
// Slots: children.
func SlimShorthandSwitch() *SlimShorthandSwitchTemplate {
	return &SlimShorthandSwitchTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"actions\">"); __err != nil {
			return
		}
		switch isAdmin {
		case true:
			if _, __err = __buf.WriteString("<button>Edit content</button>"); __err != nil {
				return
			}
		case false:
			if _, __err = __buf.WriteString("<button>Login</button>"); __err != nil {
				return
			}
		}
		if _, __err = __buf.WriteString("<button>View content</button></div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for SlimShorthandSwitchTemplate and returns a new instance.
func (t *SlimShorthandSwitchTemplate) Slot(name string, templates ...goht.Template) *SlimShorthandSwitchTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlimShorthandSwitchTemplate.
func (t *SlimShorthandSwitchTemplate) WithChildren(templates ...goht.Template) *SlimShorthandSwitchTemplate {
	return t.Slot("children", templates...)
}

// Haml supported splitting long code lines across multiple lines
// using a comma. Each line that continues the statement must be indented
// one additional level. To keep continuing the statement, you can
// end the line with a comma.

type HamlLongStatementTemplate struct {
	goht.SlotTemplate
}

// HamlLongStatement returns a new instance of HamlLongStatementTemplate.
// Slots: children.
func HamlLongStatement() *HamlLongStatementTemplate {
	return &HamlLongStatementTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"actions\">\n"); __err != nil {
			return
		}
		action := longType{title: "Edit content", actions: "Edit content"}
		if _, __err = __buf.WriteString("</div>\n"); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(fmt.Sprintf("Title: %s", action.title))); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if action.title == "Edit content" && action.actions == "Edit content" {
			if _, __err = __buf.WriteString("<p>"); __err != nil {
				return
			}
			var __var2 string
			if __var2, __err = goht.CaptureErrors(goht.EscapeString(action.actions)); __err != nil {
				return
			}
			if _, __err = __buf.WriteString(__var2); __err != nil {
				return
			}
			if _, __err = __buf.WriteString("</p>\n"); __err != nil {
				return
			}
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlLongStatementTemplate and returns a new instance.
func (t *HamlLongStatementTemplate) Slot(name string, templates ...goht.Template) *HamlLongStatementTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlLongStatementTemplate.
func (t *HamlLongStatementTemplate) WithChildren(templates ...goht.Template) *HamlLongStatementTemplate {
	return t.Slot("children", templates...)
}

// Slim supports splitting the control code across multiple lines which
// is useful for long statements. The additional lines must be indented
// one additional level.
//
// Ending a statement with a backslash or a comma will let you break
// long statements across multiple lines.

type longType struct {
	title   string
	actions string
}

type SlimLongStatementTemplate struct {
	goht.SlotTemplate
}

// SlimLongStatement returns a new instance of SlimLongStatementTemplate.
// Slots: children.
func SlimLongStatement() *SlimLongStatementTemplate {
	return &SlimLongStatementTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"actions\">"); __err != nil {
			return
		}
		action := longType{title: "Edit content", actions: "Edit content"}
		if _, __err = __buf.WriteString("</div><p>"); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(action.actions)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</p>"); __err != nil {
			return
		}
		var __var2 string
		if __var2, __err = goht.CaptureErrors(goht.EscapeString(fmt.Sprintf("Title: %s", action.title))); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var2); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for SlimLongStatementTemplate and returns a new instance.
func (t *SlimLongStatementTemplate) Slot(name string, templates ...goht.Template) *SlimLongStatementTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlimLongStatementTemplate.
func (t *SlimLongStatementTemplate) WithChildren(templates ...goht.Template) *SlimLongStatementTemplate {
	return t.Slot("children", templates...)
}
