// Code generated by GoHT v0.8.5 - DO NOT EDIT.
// https://github.com/stackus/goht

package example

import "context"
import "io"
import "github.com/stackus/goht"

type User struct {
	Name string
	Age  int
}

// GoHT templates can be created as methods on any type that allows for method definitions
//
// The following will create a Details method on the User type. It will be called like so:
//
//   user := User{Name: "John", Age: 30}
//   user.Details().Render(ctx, w))
//
// It can also be called on using the `@render` command in a GoHT template:
//
//   @render u.Details()

type DetailsTemplate struct {
	goht.SlotTemplate
}

// Details returns a new instance of DetailsTemplate.
// Slots: children.
func (u User) Details() *DetailsTemplate {
	return &DetailsTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"name\">User name: "); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(u.Name)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</div>\n<div class=\"age\">\nUser Age:\n"); __err != nil {
			return
		}
		var __var2 string
		if __var2, __err = goht.CaptureErrors(goht.FormatString("%d", u.Age)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var2); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("\n</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for DetailsTemplate and returns a new instance.
func (t *DetailsTemplate) Slot(name string, templates ...goht.Template) *DetailsTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for DetailsTemplate.
func (t *DetailsTemplate) WithChildren(templates ...goht.Template) *DetailsTemplate {
	return t.Slot("children", templates...)
}

type HamlDetailsTemplate struct {
	goht.SlotTemplate
}

// HamlDetails returns a new instance of HamlDetailsTemplate.
// Slots: children.
func (u User) HamlDetails() *HamlDetailsTemplate {
	return &HamlDetailsTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"name\">User name: "); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(u.Name)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</div>\n<div class=\"age\">\nUser Age:\n"); __err != nil {
			return
		}
		var __var2 string
		if __var2, __err = goht.CaptureErrors(goht.FormatString("%d", u.Age)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var2); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("\n</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlDetailsTemplate and returns a new instance.
func (t *HamlDetailsTemplate) Slot(name string, templates ...goht.Template) *HamlDetailsTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlDetailsTemplate.
func (t *HamlDetailsTemplate) WithChildren(templates ...goht.Template) *HamlDetailsTemplate {
	return t.Slot("children", templates...)
}

type SlimDetailsTemplate struct {
	goht.SlotTemplate
}

// SlimDetails returns a new instance of SlimDetailsTemplate.
// Slots: children.
func (u User) SlimDetails() *SlimDetailsTemplate {
	return &SlimDetailsTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<div class=\"name\">User name: "); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(u.Name)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</div><div class=\"age\">User Age:"); __err != nil {
			return
		}
		var __var2 string
		if __var2, __err = goht.CaptureErrors(goht.EscapeString(goht.FormatString("%d", u.Age))); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var2); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</div>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for SlimDetailsTemplate and returns a new instance.
func (t *SlimDetailsTemplate) Slot(name string, templates ...goht.Template) *SlimDetailsTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlimDetailsTemplate.
func (t *SlimDetailsTemplate) WithChildren(templates ...goht.Template) *SlimDetailsTemplate {
	return t.Slot("children", templates...)
}
