// Code generated by GoHT v0.9.1 - DO NOT EDIT.
// https://github.com/stackus/goht

package tags

import "context"
import "io"
import "github.com/stackus/goht"

// In HAML it is possible to include an object in the tag
// declaration to make the addition of classes and ids easier.
// This is done by using a pair of square brackets after the
// tag, id, or class declaration.
//
// The object used will need to implement one or both of the
// following methods:
// - ObjectID() string
// - ObjectClass() string

type Foo struct {
	ID string
}

func (f *Foo) ObjectID() string {
	return f.ID
}

func (f *Foo) ObjectClass() string {
	return "foo"
}

// if obj below has the id "bar" then the output will be:
// <article id="foo_bar" class="foo">Foo article</article>

type ObjectRefsTemplate struct {
	goht.SlotTemplate
}

// ObjectRefs returns a new instance of ObjectRefsTemplate.
// Slots: children.
func ObjectRefs(obj Foo) *ObjectRefsTemplate {
	return &ObjectRefsTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<article"); __err != nil {
			return
		}
		if __var1 := goht.ObjectID(obj); __var1 != "" {
			if _, __err = __buf.WriteString(" id=\"" + __var1 + "\""); __err != nil {
				return
			}
		}
		var __var2 string
		__var2, __err = goht.BuildClassList(goht.ObjectClass(obj))
		if __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" class=\"" + __var2 + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(">Foo article</article>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for ObjectRefsTemplate and returns a new instance.
func (t *ObjectRefsTemplate) Slot(name string, templates ...goht.Template) *ObjectRefsTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for ObjectRefsTemplate.
func (t *ObjectRefsTemplate) WithChildren(templates ...goht.Template) *ObjectRefsTemplate {
	return t.Slot("children", templates...)
}

type HamlObjectRefsTemplate struct {
	goht.SlotTemplate
}

// HamlObjectRefs returns a new instance of HamlObjectRefsTemplate.
// Slots: children.
func HamlObjectRefs(obj Foo) *HamlObjectRefsTemplate {
	return &HamlObjectRefsTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<article"); __err != nil {
			return
		}
		if __var1 := goht.ObjectID(obj); __var1 != "" {
			if _, __err = __buf.WriteString(" id=\"" + __var1 + "\""); __err != nil {
				return
			}
		}
		var __var2 string
		__var2, __err = goht.BuildClassList(goht.ObjectClass(obj))
		if __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" class=\"" + __var2 + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(">Foo article</article>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlObjectRefsTemplate and returns a new instance.
func (t *HamlObjectRefsTemplate) Slot(name string, templates ...goht.Template) *HamlObjectRefsTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlObjectRefsTemplate.
func (t *HamlObjectRefsTemplate) WithChildren(templates ...goht.Template) *HamlObjectRefsTemplate {
	return t.Slot("children", templates...)
}

// You may include a prefix to be used with the id and class.
var prefixVar = "article"

type PrefixedObjectRefsTemplate struct {
	goht.SlotTemplate
}

// PrefixedObjectRefs returns a new instance of PrefixedObjectRefsTemplate.
// Slots: children.
func PrefixedObjectRefs(obj Foo) *PrefixedObjectRefsTemplate {
	return &PrefixedObjectRefsTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<article"); __err != nil {
			return
		}
		if __var1 := goht.ObjectID(obj, "prefix"); __var1 != "" {
			if _, __err = __buf.WriteString(" id=\"" + __var1 + "\""); __err != nil {
				return
			}
		}
		var __var2 string
		__var2, __err = goht.BuildClassList(goht.ObjectClass(obj, "prefix"))
		if __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" class=\"" + __var2 + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(">Foo article with id \"prefix_foo_bar\" and class \"prefix_foo\"</article>\n<article"); __err != nil {
			return
		}
		if __var3 := goht.ObjectID(obj, prefixVar); __var3 != "" {
			if _, __err = __buf.WriteString(" id=\"" + __var3 + "\""); __err != nil {
				return
			}
		}
		var __var4 string
		__var4, __err = goht.BuildClassList(goht.ObjectClass(obj, prefixVar))
		if __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" class=\"" + __var4 + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(">Foo article with id \"article_foo_bar\" and class \"article_foo\"</article>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for PrefixedObjectRefsTemplate and returns a new instance.
func (t *PrefixedObjectRefsTemplate) Slot(name string, templates ...goht.Template) *PrefixedObjectRefsTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for PrefixedObjectRefsTemplate.
func (t *PrefixedObjectRefsTemplate) WithChildren(templates ...goht.Template) *PrefixedObjectRefsTemplate {
	return t.Slot("children", templates...)
}

type HamlPrefixedObjectRefsTemplate struct {
	goht.SlotTemplate
}

// HamlPrefixedObjectRefs returns a new instance of HamlPrefixedObjectRefsTemplate.
// Slots: children.
func HamlPrefixedObjectRefs(obj Foo) *HamlPrefixedObjectRefsTemplate {
	return &HamlPrefixedObjectRefsTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<article"); __err != nil {
			return
		}
		if __var1 := goht.ObjectID(obj, "prefix"); __var1 != "" {
			if _, __err = __buf.WriteString(" id=\"" + __var1 + "\""); __err != nil {
				return
			}
		}
		var __var2 string
		__var2, __err = goht.BuildClassList(goht.ObjectClass(obj, "prefix"))
		if __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" class=\"" + __var2 + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(">Foo article with id \"prefix_foo_bar\" and class \"prefix_foo\"</article>\n<article"); __err != nil {
			return
		}
		if __var3 := goht.ObjectID(obj, prefixVar); __var3 != "" {
			if _, __err = __buf.WriteString(" id=\"" + __var3 + "\""); __err != nil {
				return
			}
		}
		var __var4 string
		__var4, __err = goht.BuildClassList(goht.ObjectClass(obj, prefixVar))
		if __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" class=\"" + __var4 + "\""); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(">Foo article with id \"article_foo_bar\" and class \"article_foo\"</article>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlPrefixedObjectRefsTemplate and returns a new instance.
func (t *HamlPrefixedObjectRefsTemplate) Slot(name string, templates ...goht.Template) *HamlPrefixedObjectRefsTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlPrefixedObjectRefsTemplate.
func (t *HamlPrefixedObjectRefsTemplate) WithChildren(templates ...goht.Template) *HamlPrefixedObjectRefsTemplate {
	return t.Slot("children", templates...)
}
