// Code generated by GoHT v0.9.1 - DO NOT EDIT.
// https://github.com/stackus/goht

package unescape

import "context"
import "io"
import "github.com/stackus/goht"

// The text from variables are assumed to need HTML escaping. If you
// want to include raw HTML, or you have already processed the variable
// then you will need to unescape the text. This is accomplished with
// the `!` operator.
// Use care when using the unescape operator. You should only use it
// when you are sure that the text is safe. If you are unsure, then
// you should use the default escaping.

type UnescapeCodeTemplate struct {
	goht.SlotTemplate
}

// UnescapeCode returns a new instance of UnescapeCodeTemplate.
// Slots: children.
func UnescapeCode() *UnescapeCodeTemplate {
	return &UnescapeCodeTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>"); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString("This is <em>NOT</em> unescaped HTML. (Ampersands everywhere!)")); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</p>\n<p>"); __err != nil {
			return
		}
		var __var2 string
		if __var2, __err = goht.CaptureErrors("This <em>is</em> unescaped HTML."); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var2); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for UnescapeCodeTemplate and returns a new instance.
func (t *UnescapeCodeTemplate) Slot(name string, templates ...goht.Template) *UnescapeCodeTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for UnescapeCodeTemplate.
func (t *UnescapeCodeTemplate) WithChildren(templates ...goht.Template) *UnescapeCodeTemplate {
	return t.Slot("children", templates...)
}

type HamlUnescapeCodeTemplate struct {
	goht.SlotTemplate
}

// HamlUnescapeCode returns a new instance of HamlUnescapeCodeTemplate.
// Slots: children.
func HamlUnescapeCode() *HamlUnescapeCodeTemplate {
	return &HamlUnescapeCodeTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>"); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString("This is <em>NOT</em> unescaped HTML. (Ampersands everywhere!)")); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</p>\n<p>"); __err != nil {
			return
		}
		var __var2 string
		if __var2, __err = goht.CaptureErrors("This <em>is</em> unescaped HTML."); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var2); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlUnescapeCodeTemplate and returns a new instance.
func (t *HamlUnescapeCodeTemplate) Slot(name string, templates ...goht.Template) *HamlUnescapeCodeTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlUnescapeCodeTemplate.
func (t *HamlUnescapeCodeTemplate) WithChildren(templates ...goht.Template) *HamlUnescapeCodeTemplate {
	return t.Slot("children", templates...)
}

type SlimUnescapeCodeTemplate struct {
	goht.SlotTemplate
}

// SlimUnescapeCode returns a new instance of SlimUnescapeCodeTemplate.
// Slots: children.
func SlimUnescapeCode() *SlimUnescapeCodeTemplate {
	return &SlimUnescapeCodeTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>"); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString("This is <em>is</em> escaped HTML. (Ampersands everywhere!)")); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</p><p>"); __err != nil {
			return
		}
		var __var2 string
		if __var2, __err = goht.CaptureErrors("This is <em>NOT</em> escaped HTML."); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var2); __err != nil {
			return
		}
		if _, __err = __buf.WriteString("</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for SlimUnescapeCodeTemplate and returns a new instance.
func (t *SlimUnescapeCodeTemplate) Slot(name string, templates ...goht.Template) *SlimUnescapeCodeTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for SlimUnescapeCodeTemplate.
func (t *SlimUnescapeCodeTemplate) WithChildren(templates ...goht.Template) *SlimUnescapeCodeTemplate {
	return t.Slot("children", templates...)
}

// It can also affect the interpolated values.

type UnescapeInterpolationTemplate struct {
	goht.SlotTemplate
}

// UnescapeInterpolation returns a new instance of UnescapeInterpolationTemplate.
// Slots: children.
func UnescapeInterpolation() *UnescapeInterpolationTemplate {
	return &UnescapeInterpolationTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var html = "<em>is</em>"
		if _, __err = __buf.WriteString("<p>This "); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(html)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" is escaped. (Ampersands everywhere!)</p>\n<p>This "); __err != nil {
			return
		}
		var __var2 string
		if __var2, __err = goht.CaptureErrors(html); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var2); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" is NOT escaped.</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for UnescapeInterpolationTemplate and returns a new instance.
func (t *UnescapeInterpolationTemplate) Slot(name string, templates ...goht.Template) *UnescapeInterpolationTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for UnescapeInterpolationTemplate.
func (t *UnescapeInterpolationTemplate) WithChildren(templates ...goht.Template) *UnescapeInterpolationTemplate {
	return t.Slot("children", templates...)
}

type HamlUnescapeInterpolationTemplate struct {
	goht.SlotTemplate
}

// HamlUnescapeInterpolation returns a new instance of HamlUnescapeInterpolationTemplate.
// Slots: children.
func HamlUnescapeInterpolation() *HamlUnescapeInterpolationTemplate {
	return &HamlUnescapeInterpolationTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		var html = "<em>is</em>"
		if _, __err = __buf.WriteString("<p>This "); __err != nil {
			return
		}
		var __var1 string
		if __var1, __err = goht.CaptureErrors(goht.EscapeString(html)); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var1); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" is escaped. (Ampersands everywhere!)</p>\n<p>This "); __err != nil {
			return
		}
		var __var2 string
		if __var2, __err = goht.CaptureErrors(html); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(__var2); __err != nil {
			return
		}
		if _, __err = __buf.WriteString(" is NOT escaped.</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlUnescapeInterpolationTemplate and returns a new instance.
func (t *HamlUnescapeInterpolationTemplate) Slot(name string, templates ...goht.Template) *HamlUnescapeInterpolationTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlUnescapeInterpolationTemplate.
func (t *HamlUnescapeInterpolationTemplate) WithChildren(templates ...goht.Template) *HamlUnescapeInterpolationTemplate {
	return t.Slot("children", templates...)
}

// The plain text that you write into your Goht templates will not be
// altered by the addition of the `!` operator. It is expected that this
// text has already been HTML escaped properly.

type UnescapeTextTemplate struct {
	goht.SlotTemplate
}

// UnescapeText returns a new instance of UnescapeTextTemplate.
// Slots: children.
func UnescapeText() *UnescapeTextTemplate {
	return &UnescapeTextTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>This <em>is</em> HTML.</p>\n<p>This <em>is</em> HTML.</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for UnescapeTextTemplate and returns a new instance.
func (t *UnescapeTextTemplate) Slot(name string, templates ...goht.Template) *UnescapeTextTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for UnescapeTextTemplate.
func (t *UnescapeTextTemplate) WithChildren(templates ...goht.Template) *UnescapeTextTemplate {
	return t.Slot("children", templates...)
}

type HamlUnescapeTextTemplate struct {
	goht.SlotTemplate
}

// HamlUnescapeText returns a new instance of HamlUnescapeTextTemplate.
// Slots: children.
func HamlUnescapeText() *HamlUnescapeTextTemplate {
	return &HamlUnescapeTextTemplate{SlotTemplate: goht.NewSlotTemplate(func(ctx context.Context, __w io.Writer, __slots goht.Slots) (__err error) {
		__buf, __isBuf := __w.(goht.Buffer)
		if !__isBuf {
			__buf = goht.GetBuffer()
			defer goht.ReleaseBuffer(__buf)
		}
		if _, __err = __buf.WriteString("<p>This <em>is</em> HTML.</p>\n<p>This <em>is</em> HTML.</p>\n"); __err != nil {
			return
		}
		if !__isBuf {
			_, __err = __w.Write(__buf.Bytes())
		}
		return
	}, "children")}
}

// Slot sets a named slot for HamlUnescapeTextTemplate and returns a new instance.
func (t *HamlUnescapeTextTemplate) Slot(name string, templates ...goht.Template) *HamlUnescapeTextTemplate {
	next := *t
	next.SlotTemplate = t.SlotTemplate.Slot(name, templates...)
	return &next
}

// WithChildren sets the "children" slot for HamlUnescapeTextTemplate.
func (t *HamlUnescapeTextTemplate) WithChildren(templates ...goht.Template) *HamlUnescapeTextTemplate {
	return t.Slot("children", templates...)
}
